<?php

Function get_schema_lotto_max_stats(&$schema){
   $schema['lotto_max_stats'] = array(
  'description' => 'TODO: please describe this table!',
  'fields' => array(
    'lmxsid' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'serial',
      'not null' => TRUE,
    ),
    'stat_type' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'last_updated' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'last_id' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'draw_sequence' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's1' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's2' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's3' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's4' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's5' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's6' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's7' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's8' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's9' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's10' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's11' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's12' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's13' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's14' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's15' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's16' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's17' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's18' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's19' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's20' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's21' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's22' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's23' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's24' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's25' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's26' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's27' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's28' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's29' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's30' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's31' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's32' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's33' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's34' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's35' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's36' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's37' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's38' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's39' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's40' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's41' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's42' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's43' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's44' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's45' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's46' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's47' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's48' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
    's49' => array(
      'description' => 'TODO: please describe this field!',
      'type' => 'int',
      'not null' => FALSE,
    ),
  ),
  'primary key' => array('lmxsid'),
);
}
?>
