<?php
// $Id: emf_interspire.module,v 1.1 2010/06/03 14:02:49 bonked Exp $

/**
 * @file
 * Drupal hooks for Interspire EMF plug-in
 *
 * @author Kurt Maet <kurt@coworks.be>
 */

/**
 * Implementation of hook_menu().
 */
function emf_interspire_menu() {

  // settings
  $items['admin/settings/emf_interspire'] = array(
    'title' => 'Interspire',
    'description' => 'Configure Interspire settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('emf_interspire_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'emf_interspire.settings.inc',
  );

  return $items;
}

/**
 * Implementation of hook_emf_info().
 */
function emf_interspire_emf_info() {
  return array(
    'name' => 'Interspire',
    'file' => 'emf_interspire.api.inc',
  );
}