<?php
//module_load_include('inc', 'mt_mcq','mcq_node_setup');
module_load_include('inc', 'mt_mcq','mt_mcq_add_form');
module_load_include('inc', 'mt_mcq','MCQ');
module_load_include('inc', 'mt_mcq','mt_mcq_admin_menu');
module_load_include('inc', 'mt_mcq','mt_mcq_manage_form');
module_load_include('inc', 'mt_mcq','mt_mcq_import_form');
module_load_include('inc', 'mt_mcq','mcq_extract_dummytext_form');



/*
 * implements hook_form_alter
 */
function mt_mcq_form_alter(&$form, &$form_state, $form_id){
   //$form_node=$form['#node'];
   // if(!empty($form['#node_edit_form'])){ //&& $form_node->type=='mcq'){
         if( $form_id == 'mcq_node_form'  ){
        mt_mcq_node_form($form, $form_state);
    }
    
}

/*
 * prepare mcq node based on node add/edit form data
 */
function prepare_mcq_node(&$node){
        $mcq_title = substr($node->question_text, 0, 50);
        $node->title = $mcq_title;
        
        if ($node->answer_a == 1){
                    $answer = 'a'; 
                } elseif ($node->answer_b == 1){
                    $answer = 'b' ;
                } elseif ($node->answer_c == 1){
                    $answer = 'c' ;
                } elseif ($node->answer_d == 1){
                    $answer = 'd' ;
                } elseif  ($node->answer_e == 1){
                    $answer = 'e';
                } else $answer = '';
        if ($node->answer == null || !isset($node->answer) ) { $node->answer = $answer; }
        
	if ($node->exam == null || !isset($node->exam) ) { $node->exam = $node->aspiring_exam; }
	
       switch($node->exam){
            case 2:
                $exam_level = $node->aspiring_exam_can;
                break;
            case 3:
                $exam_level = $node->aspiring_exam_us;
                break;
            case 4:
                $exam_level = $node->aspiring_exam_uk;
                break;
            case 5:
                $exam_level = $node->aspiring_exam_au;
                break;
            default:
                $exam_level = NULL;
                break;
            
        }
	if ($node->exam_level == null || !isset($node->exam_level) ) { $node->exam_level = $exam_level; }
        
        //these are not needed at the moment on the add/edit form
        $node->validity_yn = 0; //$form_data['validity_yn'];
        $node->objection_yn = 0; //$form_data['objection_yn'];
        $node->disc_board_yn = 0; //$form_data['disc_board_yn'];
}

/*
 * implements hook_node_insert()
 * function gets called at the time of node insert into the db
 * all mcq fields are added to the node object, hence into the db
 */
function mt_mcq_node_insert($node){
    if($node->type == 'mcq' && isset($node->question_text)){
        
    /*
    * prepare mcq node based on node add/edit form data
    */
    prepare_mcq_node($node);
                
        $qid =db_insert('mcq_question_bank')
            ->fields(array(
            'qid'=>NULL,
            'nid'=>$node->nid,
            'vid'=>$node->vid,
            'question_text'=>$node->question_text,
            'choice_a'=>$node->choice_a,
            'choice_b'=>$node->choice_b,
            'choice_c'=>$node->choice_c,
            'choice_d'=>$node->choice_d,
            'choice_e'=>$node->choice_e,
            'question_media_yn'=>$node->question_media_yn,   
            'speciality'=>$node->speciality,
            'sub_speciality'=>$node->sub_speciality
                ))
          ->execute();
        
        db_insert('mcq_answer_bank')
        ->fields(array(
            'qid'=>$qid,
            'answer'=>$node->answer,
            'conf_rating'=>$node->conf_rating,
            'notes'=>$node->notes,
            'notes_a'=>$node->notes_a,
            'notes_b'=>$node->notes_b,
            'notes_c'=>$node->notes_c,
            'notes_d'=>$node->notes_d,
            'notes_e'=>$node->notes_e,
            'exam'=>$node->exam,
            'exam_level'=>$node->exam_level,
            'expert_level'=>$node->expert_level,
            'hints_yn'=>$node->hints_yn,
            'validity_yn'=>$node->validity_yn,
            'objection_yn'=>$node->objection_yn,
            'disc_board_yn'=>$node->disc_board_yn,
            
        ))
        ->execute();
           
    }
}

/*
 * implements hook_node_update
 * same as hook_node_insert, except that it checks if node entry alredy present
 */
function mt_mcq_node_update($node){
    if(db_query('SELECT qid FROM {mcq_question_bank} WHERE nid=:nid', array(':nid'=>$node->nid))->fetchfield()){
        
        prepare_mcq_node($node);
        
        db_update('mcq_question_bank')
        ->fields(array(
            'nid'=>$node->nid,
            'vid'=>$node->vid,
            'question_text'=>$node->question_text,
            'choice_a'=>$node->choice_a,
            'choice_b'=>$node->choice_b,
            'choice_c'=>$node->choice_c,
            'choice_d'=>$node->choice_d,
            'choice_e'=>$node->choice_e,
            'question_media_yn'=>$node->question_media_yn,
            'speciality'=>$node->speciality,
            'sub_speciality'=>$node->sub_speciality
            ))
            ->condition('nid',$node->nid)
            ->execute();
        
        db_update('mcq_answer_bank')
        ->fields(array(
            'answer'=>$node->answer,
            'conf_rating'=>$node->conf_rating,
            'notes'=>$node->notes,
            'notes_a'=>$node->notes_a,
            'notes_b'=>$node->notes_b,
            'notes_c'=>$node->notes_c,
            'notes_d'=>$node->notes_d,
            'notes_e'=>$node->notes_e,
            'exam'=>$node->exam,
            'exam_level'=>$node->exam_level,
            'expert_level'=>$node->expert_level,
            'hints_yn'=>$node->hints_yn,
            'validity_yn'=>$node->validity_yn,
            'objection_yn'=>$node->objection_yn,
            'disc_board_yn'=>$node->disc_board_yn
             ))
             ->condition('qid',get_qid_by_nid($node->nid))
            ->execute();
        
        dsm('Updated existing question with qid of'.$node->qid.'and nid of'.$node->nid);
    } else mt_mcq_node_insert($node);
}

/*
 * implements hook_node_delete
 * function is called at the time of node entry
 */
function mt_mcq_node_delete($node){
    $qid=get_qid_by_nid($node->nid);
    
    db_delete('mcq_question_bank')
    ->condition('qid', $qid)
            ->execute();
    
    db_delete('mcq_answer_bank')
    ->condition('qid', $qid)
            ->execute();
}

/*
 * implements hook_node_load
 * gets called when the node is loaded into memory
 * we are attaching all the mcq fields to the node object
 */
function mt_mcq_node_load($nodes, $types){
    foreach($nodes as $node){
        if($node->type=='mcq') {
            $node = mcq_load_node_by_nid($node);
        }
           
    }
}

function get_mcq_node_by_qid($qid){
    $node = new stdClass();
    $node->type = 'mcq';

    node_object_prepare($node);
    $node->nid = get_nid_by_qid($qid);

    mcq_load_node_by_nid($node);

    return $node;
}


/*
 * implements hook_node_view
 */
function mt_mcq_node_view($node, $view_mode, $langcode){
   
  //  if($node->question_text !=''){
   //  $node->content('mcq')=array(
    //       '#question_text'=>$node->question_text,
    //       '#choice_a'=>$node->choice_a,
     //     '#choie_b'=>$node->choice_b
      // );
 //   }
}

function get_qid_by_nid($nid){
    $qid=db_query('SELECT qid FROM {mcq_question_bank} WHERE nid IN(:nids)', array(':nids'=>$nid))->fetchField();

    return $qid;
}


function get_nid_by_qid($qid){
    $nid=db_query('SELECT nid FROM {mcq_question_bank} WHERE qid IN(:qids)', array(':qids'=>$qid))->fetchField();

    return nid;
}
/*
function set_node_answer(&$node, $answer){
    switch($answer){
        case 'a':
            $node->answer_a = 1;
            $node->answer_b = 0;
            $node->answer_c = 0;
            $node->answer_d = 0;
            $node->answer_e = 0;
            break;
        case 'b':
            $node->answer_a = 0;
            $node->answer_b = 1;
            $node->answer_c = 0;
            $node->answer_d = 0;
            $node->answer_e = 0;
            break;
        case 'c':
           $node->answer_a = 0;
            $node->answer_b = 0;
            $node->answer_c = 1;
            $node->answer_d = 0;
            $node->answer_e = 0;
            break;
        case 'd':
            $node->answer_a = 0;
            $node->answer_b = 0;
            $node->answer_c = 0;
            $node->answer_d = 1;
            $node->answer_e = 0;
            break;
        case 'e':
            $node->answer_a = 0;
            $node->answer_b = 0;
            $node->answer_c = 0;
            $node->answer_d = 0;
            $node->answer_e = 1;
            break;
    }
}

/*
 * checks answer box checked
 */
/*
function get_answerbox_checked($node){
 $answer_checked=NULL;
 
 if($node->answer_a==1){
     if ($answer_checked==NULL){
         $answer_checked='a';
     } else dsm('Multiple answers have been selected. Please check'); 
 }
 
 if($node->answer_b==1){
     if ($answer_checked==NULL){
         $answer_checked='b';
     } else dsm('Multiple answers have been selected. Please check'); 
 }
 
if($node->answer_c==1){
     if ($answer_checked==NULL){
         $answer_checked='c';
     } else dsm('Multiple answers have been selected. Please check'); 
 }
 
 if($node->answer_d==1){
     if ($answer_checked==NULL){
         $answer_checked='d';
     } else dsm('Multiple answers have been selected. Please check'); 
 }
 
 if($node->answer_e==1){
     if ($answer_checked==NULL){
         $answer_checked='e';
     } else dsm('Multiple answers have been selected. Please check'); 
 }
    
    return $answer_checked;
}
*/
/*
 * @TODO add node load by mcq_node_load_mode value
 * @TODO add load hints validity objection discboard values if yn=Yes
 */
function mcq_load_node_by_nid(&$node){
    $query = db_select('mcq_question_bank','q');
    $query->join('mcq_answer_bank','a', 'q.qid=a.qid');
    $query->fields('q', array('qid','nid','vid','question_text','choice_a', 'choice_b', 'choice_c', 'choice_d', 'choice_e', 'question_media_yn', 'speciality', 'sub_speciality'));
    $query->fields('a', array('answer', 'conf_rating',  'notes', 'notes_a', 'notes_b', 'notes_c', 'notes_d', 'notes_e', 'exam', 'exam_level', 'expert_level', 'hints_yn', 'validity_yn', 'objection_yn', 'disc_board_yn'));
    $query->condition('q.nid',$node->nid);
    $result = $query->execute();
    foreach($result as $row){
        
        $node->qid = $row->qid;
        $node->question_text = $row->question_text;
        $node->choice_a = $row->choice_a;
        $node->choice_b = $row->choice_b;
        $node->choice_c = $row->choice_c;
        $node->choice_d = $row->choice_d;
        $node->choice_e = $row->choice_e;
        $node->question_media_yn = $row->question_media_yn;
        $node->speciality = $row->speciality;
        $node->sub_speciality = $row->sub_speciality;
        $node->answer = $row->answer;
        $node->conf_rating = $row->conf_rating;
        $node->notes = $row->notes;
        $node->notes_a = $row->notes_a;
        $node->notes_b = $row->notes_b;
        $node->notes_c = $row->notes_c;
        $node->notes_d = $row->notes_d;
        $node->notes_e = $row->notes_e;
        $node->exam = $row->exam;
        $node->exam_level = $row->exam_level;
        $node->expert_level = $row->expert_level;
        $node->hints_yn = $row->hints_yn;
        $node->validity_yn = $row->validity_yn;
        $node->objection_yn = $row->objection_yn;
        $node->disc_board_yn = $row->disc_board_yn;
    }
    
    return $node;
}