<?php
 
  
  function get_user_role_by_order($order){
      $order_id = $order->order_id;
      $uid = $order->uid;
      
      $order_product = db_select('uc_order_products', 'op')->fields('op')->condition('order_id', $order_id)->execute()->fetchAssoc();
      $nid = $order_product['nid'];
      $order_product_id = $order_product['order_product_id'];
      $order_product_title = $order_product['title'];
      
      $roles_product = db_select('uc_roles_products', 'rp')->fields('rp')->condition('nid', $nid)->execute()->fetchAssoc();
      $rid = $roles_product['rid'];
      $role_duration = $roles_product['duration'];
      $role_granularity = $roles_product['granularity'];
      
      $role_expiration = db_select('uc_roles_expirations', 're')
				    ->fields('re', array('expiration'))
				    ->condition('uid', $uid)
				    ->condition('rid', $rid)
				    ->execute()
				    ->fetchAssoc();
      
      $user_role = new stdClass();
      $user_role->order_id =  $order_id;//order->oid
      $user_role->uid = $uid;//$ordier->uid
      $user_role->nid = $nid;//uc_order_products(oid)
      $user_role->order_product_id = $order_product_id; ////uc_order_products(oid)
      $user_role->role_title = $order_product_title;//uc_order_products(oid)
      $user_role->rid = $rid ;//uc_roles_prodtucs(nid)
      $user_role->role_duration = $role_duration;//uc_roles_products(nid)
      $user_role->role_granularity = $role_granularity;//uc_roles_products(nid)
      $user_role->expiration_timestamp = $role_expiration['expiration']; //uc_roles_expiration(uid, rid);
      
      return $user_role;
  }
  
  /*
   * only for free user role, missing order details
   */
  function get_free_user_role_by_uid($uid){      
      $role_expiration = db_select('uc_roles_expirations', 'rex')->fields('rex')->condition('uid', $uid)->execute()->fetchAssoc();
      $rid = $role_expiration['rid'];      
      $role_expiration_timestamp = $role_expiration['expiration'];
      
      $roles_product = db_select('uc_roles_products', 'rp')->fields('rp')->condition('rid', $rid)->execute()->fetchAssoc();
      $nid = $roles_product['nid'];
      $role_duration = $roles_product['duration'];
      $role_granularity = $roles_product['granularity'];
      
      $node = db_select('node', 'nd')->fields('nd')->condition('nid', $nid)->execute()->fetchAssoc();
      $role_product_title = $node['title'];
      
      $role_duration = $roles_product['duration'];
      $role_granularity = $roles_product['granularity'];
      
      $user_role = new stdClass();
      $user_role->uid = $uid;//$ordier->uid
      $user_role->nid = $nid;//uc_order_products(oid)
      $user_role->role_title = $role_product_title;//uc_order_products(oid)
      $user_role->rid = $rid ;//uc_roles_prodtucs(nid)
      $user_role->role_duration = $role_duration;//uc_roles_products(nid)
      $user_role->role_granularity = $role_granularity;//uc_roles_products(nid)
      $user_role->expiration_timestamp = $role_expiration_timestamp; //uc_roles_expiration(uid, rid);
      
      return $user_role;
  }
  
function setup_uc_checkout_form(){
     //move counyry field up
    $checkout_billing_pane_weight = variable_get('uc_address_fields_weight');
    $checkout_billing_pane_weight['country'] = $checkout_billing_pane_weight['company'];
    variable_set('uc_address_fields_weight', $checkout_billing_pane_weight);
    
    //disable company field on the checkout form 
    $checkout_billing_pane = variable_get('uc_address_fields');
    if (array_key_exists('company', $checkout_billing_pane)){
	unset($checkout_billing_pane['company']);
	variable_set('uc_address_fields', $checkout_billing_pane);
	}
 }