<?php
/**
 * @file
 * This module provides block with a simple jQuery coundown
 *
 * Author: Marcin Pajdzik
 */

/**
 * Implements hook_theme().
 */
function jquery_countdown_timer_theme() {
  return array(
    'jquery_countdown_timer_container' => array(
      'variables' => array(),
    )
  ); 
}

/**
 * Implements hook_block_info().
 */
function jquery_countdown_timer_block_info() {
  $blocks = array();
  $blocks['jquery_countdown_timer'] = array(
    'info'  => t('jQuery Countdown Timer'),
    'cache' => DRUPAL_CACHE_GLOBAL     
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function jquery_countdown_timer_block_configure($delta) {
  $form = array();
  switch ($delta) {
    case 'jquery_countdown_timer':
      module_load_include('inc', 'date_api', 'date_api_elements');
      $form['jquery_countdown_timer_font_size'] = array(
        '#type' => 'textfield',
        '#title' => t('Timer font size'),
        '#default_value' => variable_get('jquery_countdown_timer_font_size', 28),
        '#size' => 3,
        '#maxlength' => 2,
      );
      $form['jquery_countdown_timer_date'] = array(
        '#type' => 'date_select',
        '#title' => t('Timer date'),
        '#default_value' => variable_get('jquery_countdown_timer_date', date('Y-m-d G:i:s')),
      );
      break;
  }
  return $form;
}


/**
 * Implements hook_block_save().
 */
function jquery_countdown_timer_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'jquery_countdown_timer':
      variable_set('jquery_countdown_timer_date', $edit['jquery_countdown_timer_date']);
      variable_set('jquery_countdown_timer_font_size', (int)$edit['jquery_countdown_timer_font_size']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function jquery_countdown_timer_block_view($delta = '', $edit = array()) {
  $block = '';
  switch ($delta) {
    case 'jquery_countdown_timer':
      $block['subject'] = 'Countdown';
      $block['content'] = jquery_countdown_timer_get_content();
      break;
  }
  return $block;
}

/**
 * Builds the countdown timer.
 */
function jquery_countdown_timer_get_content() {
  $path = drupal_get_path('module', 'jquery_countdown_timer');
  drupal_add_js($path . '/js/jquery_countdown_timer.js', array('type' => 'file', 'scope' => 'footer'));
  drupal_add_js($path . '/js/jquery_countdown_timer_init.js', array('type' => 'file', 'scope' => 'footer'));
  drupal_add_css($path . '/css/jquery_countdown_timer.css'); 
  $font_size = variable_get('jquery_countdown_timer_font_size', 28);
  drupal_add_css('.countdownHolder {font-size: ' . $font_size . 'px}', 'inline');
  $settings = array(
    'jquery_countdown_timer_date' => strtotime(variable_get('jquery_countdown_timer_date', date('Y-m-d G:i:s'))),
  );

  drupal_add_js(array('jquery_countdown_timer' => $settings), array('type' => 'setting', 'scope' => 'footer'));
  $content = theme('jquery_countdown_timer_container', array());

  return $content;
}

/**
 * Returns HTML for the timer container.
 * 
 * @param type $variables
 * @return string 
 */

function theme_jquery_countdown_timer_container($variables) {
  $output = '';
  $output .= "<div id='jquery-countdown-timer'></div>";
  $output .= "<div id='jquery-countdown-timer-note'></div>";
  return $output;
}