<?php

module_load_include('inc', 'mt_import_export', 'mt_import_export_admin_menu');
module_load_include('inc', 'mt_import_export','mt_import_export_forms');

/*
 * $list = array (
    array('aaa', 'bbb', 'ccc', 'dddd'),
    array('123', '456', '789'),
    array('"aaa"', '"bbb"')
);

// Create CSV file
$csv_folder     = BASEURLHERE.'/csv';
$filename 	= "sales";
$CSVFileName    = $csv_folder.'/'.$filename.'.csv';
$FileHandle     = fopen($CSVFileName, 'w') or die("can't open file");

fclose($FileHandle);
		
$fp = fopen($CSVFileName, 'w');

foreach ($csv_fields as $fields) {
	fputcsv($fp, $fields);
}
fclose($fp);

 * 
 */

function table_export($table_name, $fields_array = false, $condition_array = false) {
    $query = db_select($table_name, 'n');
    
    if($fields_array == false) {
        $query->fields('n');
    } else $query->fields('n', $fields_array);
    
    if ($condition_array == false){
    } else {
       foreach ($condition_array as $key=>$value) {
           $query->condition($key, $value );
       }
    }
        
    $results = $query->execute();
     
    $data_array =  $results->fetchAll(PDO::FETCH_ASSOC);
    
    return $data_array;
}

/* //original function
 * 
function export_csv(&$handle, $fields = array(), $delimiter = ',', $enclosure = '"') {
    $str = '';
    $escape_char = '\\';
    foreach ($fields as $value) {
      if (strpos($value, $delimiter) !== false ||
          strpos($value, $enclosure) !== false ||
          strpos($value, "\n") !== false ||
          strpos($value, "\r") !== false ||
          strpos($value, "\t") !== false ||
          strpos($value, ' ') !== false) {
        $str2 = $enclosure;
        $escaped = 0;
        $len = strlen($value);
        for ($i=0;$i<$len;$i++) {
          if ($value[$i] == $escape_char) {
            $escaped = 1;
          } else if (!$escaped && $value[$i] == $enclosure) {
            $str2 .= $enclosure;
          } else {
            $escaped = 0;
          }
          $str2 .= $value[$i];
        }
        $str2 .= $enclosure;
        $str .= $str2.$delimiter;
      } else {
        $str .= $value.$delimiter;
      }
    }
    $str = substr($str,0,-1);
    $str .= "\n";
    return fwrite($handle, $str);
  }
*/


  function export_to_csv(&$handle, $fields = array(), $delimiter = ',', $enclosure = '"') {
    $str = '';
    $escape_char = '\\';
    
     //add first row column header($key) array to the beginning of the data array
      array_unshift($fields, array_keys($fields[0]));    
    
    
    foreach ($fields as $key=>$value) {
      if (strpos($value, $delimiter) !== false ||
          strpos($value, $enclosure) !== false ||
          strpos($value, "\n") !== false ||
          strpos($value, "\r") !== false ||
          strpos($value, "\t") !== false ||
          strpos($value, ' ') !== false) {
        $str2 = $enclosure;
        $escaped = 0;
        $len = strlen($value);
        for ($i=0;$i<$len;$i++) {
          if ($value[$i] == $escape_char) {
            $escaped = 1;
          } else if (!$escaped && $value[$i] == $enclosure) {
            $str2 .= $enclosure;
          } else {
            $escaped = 0;
          }
          $str2 .= $value[$i];
        }
        $str2 .= $enclosure;
        $str .= $str2.$delimiter;
      } else {
        $str .= $value.$delimiter;
      }
    }
    $str = substr($str,0,-1);
    $str .= "\n";
    return fwrite($handle, $str);
  }
  
  
  
?>
