<?php
module_load_include('inc', 'mt_mindmaps','mt_mindmaps.services_graphmind');


/*
 * implements hook_enable
 */
function mt_mindmaps_enable(){
    services_graphmind_endpoint_new();
}

/*
 * implements hook_disable
 */
function mt_mindmaps_disable(){
    services_graphmind_endpoint_delete();
}

/*
 * implements hook_install
 */
function mt_mindmaps_install(){
    
}

/*
 * implements hook_uninstall
 */
function mt_mindmaps_uninstall(){
    
}

